### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'StrEnum'

### ISSUE THREAD

**Issue by clayne** [LucipherDev/ComfyUI-Golden-Noise#1]
```
Traceback (most recent call last):
  File "S:\stablediffusion\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\stablediffusion\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler\__init__.py", line 1, in <module>
    from .sigmas_merge import NODE_CLASS_MAPPINGS
  File "S:\stablediffusion\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler\sigmas_merge.py", line 29, in <module>
    class GraphScale(enum.StrEnum):
AttributeError: module 'enum' has no attribute 'StrEnum'

Cannot import S:\stablediffusion\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler module for custom nodes: module 'enum' has no attribute 'StrEnum'
```

**Comment by LucipherDev** [comment]
Wrong repo, you are looking for this one;- https://github.com/Extraltodeus/sigmas_tools_and_the_golden_scheduler

**Comment by clayne** [comment]
Whoops, my bad! Sorry about that.
